[package]
name = "launcher_gtk_rs"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0.73"
serde = { version = "1.0", features = ["derive"] }
gtk = { version = "0.4.4", package = "gtk4" }
webbrowser = "0.5.5"
